### ISSUE TITLE
Redmine 5 support

### ISSUE THREAD

**Issue by lifeboy** [preciousplum/customfield_checkbox_utility#1]
```
Environment:
  Redmine version                5.0.3.stable
  Ruby version                   3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  6.1.7
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
Redmine settings:
  Redmine theme                  Circle (includes JavaScript)
SCM:
  Filesystem                     
Redmine plugins:
  custom_users_as_assignees      0.0.4
  redmine_checklists             3.1.21
  redmine_contacts               4.3.6
  redmine_contacts_helpdesk      4.2.0
  redmineup_tags                 2.0.12

```

Under Redmine 5, I get an error:

**Error ID:** 
93300a11
**Details:**
Web application could not be started by the Phusion Passenger(R) application server.

Please read [the Passenger log file](https://www.phusionpassenger.com/library/admin/log_file/) (search for the Error ID) to find the details of the error.

The production log shows this:
```
W, [2023-03-06T12:34:48.681829 #3005151]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2023-03-06T12:34:48.745939 #3005151]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2023-03-06T12:34:48.746236 #3005151]  WARN -- : Creating scope :having_mail. Overwriting existing method User.having_mail.
W, [2023-03-06T12:34:57.762295 #3005196]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
W, [2023-03-06T12:34:57.816443 #3005196]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2023-03-06T12:34:57.816748 #3005196]  WARN -- : Creating scope :having_mail. Overwriting existing method User.having_mail.

```

/var/log/apache2/error.log show this:
```
App 3005700 output: Error: The application encountered the following error: expected file /var/www/redmine/plugins/customfield_checkbox_utility/lib/view_hooks.rb to define constant ViewHooks, but didn't (Zeitwerk::NameError)
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/kernel.rb:31:in `require'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:135:in `cget'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `each'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/helpers.rb:25:in `ls'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `each'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:296:in `block in eager_load_all'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `each'
App 3005700 output:     /var/lib/gems/3.0.0/gems/zeitwerk-2.6.6/lib/zeitwerk/loader.rb:294:in `eager_load_all'
App 3005700 output:     /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
App 3005700 output:     /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
App 3005700 output:     /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
App 3005700 output:     /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
App 3005700 output:     /usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
App 3005700 output:     /usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
App 3005700 output:     /usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
App 3005700 output:     /usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
App 3005700 output:     /usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
App 3005700 output:     /usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
App 3005700 output:     /usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
App 3005700 output:     /usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
App 3005700 output:     /usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
App 3005700 output:     /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
App 3005700 output:     /var/lib/gems/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
App 3005700 output:     /var/www/redmine/config/environment.rb:16:in `<top (required)>'
App 3005700 output:     config.ru:3:in `require'
App 3005700 output:     config.ru:3:in `block in <main>'
App 3005700 output:     /var/lib/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:125:in `instance_eval'
App 3005700 output:     /var/lib/gems/3.0.0/gems/rack-2.2.4/lib/rack/builder.rb:125:in `initialize'
App 3005700 output:     config.ru:1:in `new'
App 3005700 output:     config.ru:1:in `<main>'
App 3005700 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
App 3005700 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
App 3005700 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
App 3005700 output:     /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
App 3005700 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
App 3005700 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 3005700 output:     /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
[ E 2023-03-06 12:40:26.2012 3005056/T22 age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /var/www/redmine: The application encountered the following error: expected file /var/www/redmine/plugins/customfield_checkbox_utility/lib/view_hooks.rb to define constant ViewHooks, but didn't (Zeitwerk::NameError)
  Error ID: ecebc1e8
  Error details saved to: /tmp/passenger-error-KL7orZ.html

[ E 2023-03-06 12:40:26.2033 3005056/Ta age/Cor/Con/CheckoutSession.cpp:274 ]: [Client 2-4] Cannot checkout session because a spawning error occurred. The identifier of the error is ecebc1e8. Please see earlier logs for details about the error.
```

Can this easily be fixed?

**Comment by SinghNanak** [comment]
can someone make it compatible with redmine 5.0x

**Comment by formigadiablo** [comment]
Any update?

**Comment by JGallot** [comment]
HI,
a bit late,
I've made a fork here : https://github.com/JGallot/customfield_checkbox_utility
